version: '3.3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.1.8-xenial
    restart: always
    networks:
      - b5-net
    ports:
      - 27017:27017

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - b5-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.23.0
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - b5-net

networks:
  b5-net:
    driver: bridge
